### ISSUE TITLE
gcc-wrapper fails to build and there's no gcc package

### ISSUE THREAD

**Issue by chamini2** [joelteon/nixpkgs#24]
I'm setting up my Mac from scratch: uninstalled brew, new dotfiles, etc.

I installed Nix as instructed [here](https://nixos.org/wiki/Nix_on_OS_X), and when I run

    $ nix-env -qa gcc 
    error: selector ‘gcc’ matches no derivations

So I did

    $ nix-env -qa | grep gcc
    gcc-arm-embedded-4.7-2013q3-20130916
    gcc-arm-embedded-4.8-2014q1-20140314
    gcc-debug-wrapper-4.8.4
    gcc-wrapper-3.4.6
    gcc-wrapper-4.6.4
    gcc-wrapper-4.8.4
    gcc-wrapper-4.9.2
    gccgo-wrapper-4.8.4
    gccmakedep-1.0.3

After trying to

    $ nix-env -i gcc-wrapper-4.9.2

I get a lot of output, but the end is this:

    builder for ‘/nix/store/i6f9r4n7k4jdw9c5zn9rqpmlvzd2wrdg-gcc-4.9.2.drv’ failed with exit code 2
    cannot build derivation ‘/nix/store/d59g3xqd3ivg14pg2088qzbrgs4jxnyj-gcc-wrapper-4.9.2.drv’: 1 dependencies couldn't be built
    error: build of ‘/nix/store/d59g3xqd3ivg14pg2088qzbrgs4jxnyj-gcc-wrapper-4.9.2.drv’ failed

How can I install `gcc` with `nix` correctly?

**Comment by gridaphobe** [comment]
`gcc` is currently unsupported on `nix-darwin`, we use `clang` instead. So try

```
$ nix-env -i clang-wrapper-3.5.0
```

instead.

**Comment by chamini2** [comment]
I did not know that, thanks.
